### ISSUE TITLE
Throw an error when the custom_normalization.py script is run in parallel, as it require being run with only 1 worker.

### ISSUE THREAD

**Issue by Oufattole** [Oufattole/meds-torch#130]
If you run it in parallel each worker will update the metadata file binning codes multiple times, when you only want to perform this once. I'm not sure if meds-transform allows you to access n_workers for a stage via the stage_cfg command @mmcdermott as we could just check this and throw an error?

**Comment by mmcdermott** [comment]
Can't you just set the number of workers to 1 in the stage runner yaml file?

**Comment by mmcdermott** [comment]
And/or use `cfg.worker` like here: https://github.com/mmcdermott/MEDS_transforms/blob/main/src/MEDS_transforms/aggregate_code_metadata.py#L692
